### ISSUE TITLE
Unable to install using Node v0.12.4

### ISSUE THREAD

**Issue by haganbt** [bcoe/sandcastle#61]
It appears that the ```buffertools``` module is the issue. Possibly related to #60 ?

Appreciate any thoughts.

```
Ben$ npm install sandcastle --save
npm WARN package.json ms-process-handler@1.0.0 No description
|
> buffertools@2.1.3 install /Users/Ben/node_modules/sandcastle/node_modules/bufferstream/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/buffertools.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/buffertools.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Ben/node_modules/sandcastle/node_modules/bufferstream/node_modules/buffertools
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing buffertools@2.1.3
sandcastle@1.3.3 node_modules/sandcastle
├── clone@0.1.19
├── debug@2.2.0 (ms@0.7.1)
├── optimist@0.3.7 (wordwrap@0.0.3)
├── lodash@2.4.2
└── bufferstream@0.6.2 (bufferjs@2.0.0)
Ben$ node -v
v0.12.4
Ben$ npm -v
2.14.1
```

**Comment by bcoe** [comment]
@haganbt ugly error message I know! but this is actually an optional dependency of `bufferstream` that is failing -- it looks like the install was actually successful.

**Comment by haganbt** [comment]
Understood. Many thanks.
